### ISSUE TITLE
Sometimes attachments do not have URLs

### ISSUE THREAD

**Issue by stewsnooze** [rasky/trello-hipchat#3] opened 2013-10-20 15:54 UTC
I edited the aurl code to handle this (although it was a little hacky.

`
            try:
                aurl = A["data"]["attachment"]["url"]
            except:
                aurl = "http://fullfatthings.com/"
`

**Comment by rasky** [comment] 2013-10-21 10:34
In what cases an attachment doesn't have a URL?

**Comment by stewsnooze** [comment] 2013-10-21 14:48
I didn't think there was one until yesterday I got one. my last_action.id has moved on a lot since that though so I can't find the offending item. However the script was stuck for days because of the missing URL

**Comment by rasky** [comment] 2013-10-21 15:10
The fact that the script gets stuck is unfortunate, I agree. I should probably fix this so that the specific action is skipped and an error is generated instead.

I would love if you could find what specific attachment was missing its URL, that would be great to provide a proper solution to this item. I understand if you don't want to investigate, in which case we'll just wait for someone else to hit it.

**Comment by filipkis** [comment] 2013-11-27 01:31
I managed to get the same error. I happens when an attachment is uploaded and then deleted, but the upload action still stays in the actions list. The delete happened very quickly after the upload.

**Comment by rasky** [comment] 2013-11-27 10:38
OK thanks I managed to reproduce this. Basically, when an attachment is removed, the URL of the attachment is not served anymore by the Trello API (I guess that the file is really erased from the file server, so there is not a valid file URL anymore).

So, if you attach a file and then quickly remove it (before trello-hipchat runs), you will get a notification of a new attachment without an URL. Since this happens when the attachment is later removed, I guess that we should ignore the message and not notify hipchat.

**Comment by filipkis** [comment] 2013-11-27 11:01
You're welcome. Thanks for the great script! 

I agree with ignoring that message. I made a quick fix to do exactly that for myself.

**Comment by rasky** [comment] 2013-11-27 11:16
OK fixed with my push. I've also added support for card creation.

**Closed as completed** 2013-11-27 11:18 UTC
